# Generated by Django 4.0.6 on 2022-07-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('published_time', models.CharField(max_length=100)),
                ('thumbnail_url_default', models.CharField(max_length=100)),
                ('thumbnail_url_medium', models.CharField(max_length=100)),
                ('thumbnail_url_high', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-published_time',),
            },
        ),
    ]
